version: '3.8'

services:
  rasa-actions:
    build:
      context: .
      dockerfile: Dockerfile.rasa-actions
    container_name: rasa-actions
    ports:
      - "5055:5055"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./actions:/app/actions
    networks:
      - rasa-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5055/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  rasa-main:
    build:
      context: .
      dockerfile: Dockerfile.rasa-main
    container_name: rasa-main
    ports:
      - "5005:5005"
    environment:
      - ACTION_ENDPOINT_URL=http://rasa-actions:5055/webhook
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    depends_on:
      rasa-actions:
        condition: service_healthy
    networks:
      - rasa-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5005/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  rasa-network:
    driver: bridge 