services:
  - type: web
    name: rasa-chatbot
    env: docker
    dockerfilePath: ./Dockerfile.render
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /
    buildCommand: mkdir -p models
    startCommand: /app/start.sh
    port: 8000 